### ISSUE TITLE
時間軸顯示時，手抄搞分頁的調整鈕顯示與觸控位置不同

### ISSUE THREAD

**Issue by cometjc** [eyesblue/LamrimReaderStable#1]
時間軸開啟或鎖定時，手抄搞分頁的調整鈕顯示位置與拖動位置產生偏移。

調整時分隔線控制標籤會落在實際觸控位置上方，高一個時間軸高度

**Comment by eyesblue** [comment]
已於1.4.15版修正，感謝回報！
