### ISSUE TITLE
固定時間軸可能造成無法再調整分割線高度

### ISSUE THREAD

**Issue by cometjc** [eyesblue/LamrimReaderStable#2]
如果一開始將分隔線調到一半以上接近頂部(我是用手機畫面，螢幕較小)，開啟或鎖定時間軸後，

分隔線標籤就會跑到可視範圍外，上方工具列的背景，因此就按不到標籤，無法進行分隔線調整、顯示本文了。

**Comment by eyesblue** [comment]
了解，在下一個版本會修正這個問題，感謝反應問題。

**Comment by eyesblue** [comment]
已於1.4.15版修正完成，感謝回報！
